title:
author: The NrSur Catalog Team
logo: logo.png

execute:
  execute_notebooks: 'off'

latex:
  latex_documents:
    targetname: main.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/cjhaster/NRSurCatalog
  branch: main

html:
  use_issues_button: true
  use_repository_button: true
